variables:
  projectName: 'bmi-Flutter'
trigger:
- master

jobs:
  - job: Android
    pool:
     vmImage: 'macos-latest'

    steps:
      - task: FlutterInstall@0
        inputs:
            channel: 'stable'
            version: 'latest'
          
      - task: FlutterBuild@0
        inputs:
          target: 'apk'
          projectDirectory: '.'
          buildNumber: ''

      - task: AndroidSigning@3
        displayName: 'Signing and aligning APK file(s) **/*.apk'
        inputs:
          apkFiles: '**/*.apk'
          apksign: true
          apksignerKeystoreFile: $(key).keystore
          apksignerKeystorePassword: $(keypassword)
          apksignerKeystoreAlias: $(key)
          apksignerKeyPassword: $(keypassword)

      - task: CopyFiles@2
        inputs:
          SourceFolder: '.'
          contents: "**/*.apk"
          targetFolder: "$(Build.ArtifactStagingDirectory)/$(projectName)"
        displayName: "Copy signed APK to staging directory"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/$(projectName)"
          ArtifactName: "$(projectName)"
          publishLocation: "Container"