variables:
  projectName: 'bmi-Flutter'

trigger:
- master

jobs:
  - job: Android
    pool:
     vmImage: 'macos-latest'

    steps:
      - task: FlutterInstall@0
        inputs:
            channel: 'stable'
            version: 'latest'

      - task: FlutterBuild@0
        inputs:
          target: 'apk'
          projectDirectory: $(Build.SourcesDirectory/$(projectName))
          buildNumber: ''

      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/$(projectName)/android/app/build/outputs/apk/$(buildConfiguration)'
          contents: "**/app-$(buildConfiguration).apk"
          targetFolder: "$(Build.ArtifactStagingDirectory)/$(projectName)"
        displayName: "Copy unsigned APK to staging directory"

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: "$(Build.ArtifactStagingDirectory)/$(projectName)"
          ArtifactName: "$(projectName)"
          publishLocation: "Container"

        
