variables:
  pdir: 'bmi-Flutter'

trigger:
- master

jobs:
  - job: Android
    pool:
     vmImage: 'macos-latest'

    steps:
      - task: FlutterInstall@0
        inputs:
            channel: 'stable'
            version: 'latest'

      - task: FlutterBuild@0
        inputs:
          target: 'apk'
          projectDirectory: $(Build.SourcesDirectory)


# - task: AndroidSigning@3
#   displayName: 'Signing and aligning APK file(s) **/*.apk'
#   inputs:
#     apkFiles: '**/*.apk'
#     apksign: true
#     apksignerKeystoreFile: key.jks
#     apksignerKeystorePassword: $(keypassword)
#     apksignerKeystoreAlias: $(key)
#     apksignerKeyPassword: $(keypassword)
# - task: DownloadBuildArtifacts@1
#   inputs:
#     buildType: 'current'
#     downloadType: 'single'
#     artifactName: 'demo'
#     downloadPath: '$(System.ArtifactsDirectory)'
