variables:
  pdir: 'bmi-Flutter'

trigger:
- master

jobs:
  - job: Android
    pool:
     vmImage: 'macos-latest'

    steps:
      - task: FlutterInstall@0
        inputs:
            channel: 'stable'
            version: 'latest'

      - task: FlutterBuild@0
        inputs:
          target: 'apk'
          projectDirectory: $(Build.SourcesDirectory)
          buildNumber: ''
      
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)'
          artifactType: 'pipeline'
          artifactName: 'drop'
        
